
(()=>{const $=q=>Lab.select(q),A=$('#agonist'),B=$('#antag'),NS='http://www.w3.org/2000/svg';let moved=false;
function aval(){return +A.value/20}function bval(){return +B.value/20}const kd=1.5,ki=1.5;
function fractions(a=aval(),b=bval()){let den=1+a/kd+b/ki;return {ag:(a/kd)/den,an:(b/ki)/den}}
function label(v,zero=false){return v==0&&zero?'なし':v<25?'少ない':v<65?'中くらい':'多い'}
function build(){let g=$('#rec');g.innerHTML='';for(let i=0;i<8;i++){let x=95+i*70,p=document.createElementNS(NS,'path');p.setAttribute('d',`M${x-15} 175 V147 Q${x} 127 ${x+15} 147 V175`);p.setAttribute('fill','white');p.setAttribute('stroke','#315b9a');p.setAttribute('stroke-width','7');p.setAttribute('stroke-linecap','round');p.dataset.x=x;g.appendChild(p);let t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',203);t.setAttribute('text-anchor','middle');t.setAttribute('font-size','10');t.setAttribute('font-weight','800');t.textContent='OFF';g.appendChild(t)}}
function draw(){let f=fractions(),nag=moved?Math.round(f.ag*8):0,nan=moved?Math.min(8-nag,Math.round(f.an*8)):0,g=$('#bound'),free=$('#freeDrugs');g.innerHTML='';free.innerHTML='';let ch=$('#rec').children;
for(let i=0;i<8;i++){let p=ch[i*2],t=ch[i*2+1],type=i<nag?'ag':i<nag+nan?'an':'free';p.setAttribute('stroke',type==='ag'?'#df665f':type==='an'?'#667085':'#315b9a');t.textContent=type==='ag'?'ON':type==='an'?'BLOCK':'OFF';t.setAttribute('fill',type==='ag'?'#df665f':type==='an'?'#667085':'#667085');if(type!=='free'){let q=document.createElementNS(NS,'circle');q.setAttribute('cx',p.dataset.x);q.setAttribute('cy',130);q.setAttribute('r',10);q.setAttribute('fill',type==='ag'?'#df665f':'#667085');g.appendChild(q)}}
for(let i=0;i<Math.min(9,Math.ceil(aval()*1.5));i++){let q=document.createElementNS(NS,'circle');q.setAttribute('cx',55+(i*67)%540);q.setAttribute('cy',50+(i%3)*18);q.setAttribute('r',7);q.setAttribute('fill','#df665f');q.setAttribute('opacity','.65');free.appendChild(q)}
for(let i=0;i<Math.min(9,Math.ceil(bval()*1.5));i++){let q=document.createElementNS(NS,'circle');q.setAttribute('cx',85+(i*73)%520);q.setAttribute('cy',95+(i%2)*18);q.setAttribute('r',7);q.setAttribute('fill','#667085');q.setAttribute('opacity','.7');free.appendChild(q)}
let ef=moved?f.ag*100:0;$('#on').textContent=`${nag} / 8`;$('#blocked').textContent=`${nan} / 8`;$('#resp').textContent=Math.round(ef)+'%';$('#responseBar').setAttribute('width',240*ef/100);$('#responseLabel').textContent='細胞の反応：'+(ef<25?'弱い':ef<60?'中くらい':'強い')}
function graph(){let base=[],cur=[];for(let v=0;v<=100;v++){let a=v/20,fb=fractions(a,0).ag,fc=fractions(a,bval()).ag;base.push(`${70+v/100*720},${250-fb*220}`);cur.push(`${70+v/100*720},${250-fc*220}`)}$('#baseCurve').setAttribute('points',base.join(' '));$('#curve').setAttribute('points',cur.join(' '));let f=fractions().ag;$('#dot').setAttribute('cx',70+(+A.value)/100*720);$('#dot').setAttribute('cy',250-f*220)}
function render(){$('#aText').textContent=label(+A.value);$('#bText').textContent=label(+B.value,true);draw();graph()}A.oninput=render;B.oninput=render;$('#move').onclick=()=>{moved=true;$('#status').textContent='受容体を取り合っている';draw()};$('#reset').onclick=()=>{A.value=55;B.value=0;moved=false;$('#status').textContent='薬を動かしてみよう';render()};build();render()})();

