const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const M=require('../assets/js/autonomic-models.js'),root=path.resolve(__dirname,'..');
for(const kind of ['16','17','18'])for(let a=0;a<=100;a+=5)for(let b=0;b<=100;b+=5){const s=M.state(kind,a,b);assert(Math.abs(s.on+s.blocked+s.free-1)<1e-12);assert(s.on>=0&&s.blocked>=0);assert(M.state(kind,a+1,b).response>=s.response);assert(M.state(kind,a,b+1).response<=s.response);assert(s.rate>0&&s.diameter>0);}
for(const kind of ['16','17','18']){const s=M.state(kind,0,100);assert.equal(s.on,0);assert(s.blocked>0);assert.equal(s.rate,1);assert.equal(s.force,1);assert.equal(s.diameter,1);assert.equal(s.secretion,1);assert(M.state(kind,1e8,100).response>.9999);}
assert(M.state('16',55,0).rate>1&&M.state('16',55,0).force>1);assert(M.state('17',55,0).diameter>1);assert(M.state('18',55,0).rate<1&&M.state('18',55,0).diameter<1&&M.state('18',55,0).secretion>1);
const element=()=>({attrs:{},children:[],value:'',textContent:'',style:{setProperty(k,v){this[k]=v}},setAttribute(k,v){this.attrs[k]=String(v)},append(...e){this.children.push(...e)}});
for(const [kind,slug]of [['16','beta1'],['17','beta2'],['18','parasympathetic']]){
 const html=fs.readFileSync(path.join(root,`pharmacology_lab_${kind}_${slug}.html`),'utf8'),els=new Map();for(const m of html.matchAll(/<[^>]+\bid="([^"]+)"[^>]*>/g)){const e=element();e.value=(m[0].match(/value="([^"]+)"/)||[])[1]||'';els.set('#'+m[1],e);}
 const $=s=>els.get(s),ctx={document:{body:{dataset:{lab:kind}},querySelector:$,createElement:element},console};ctx.window=ctx;vm.createContext(ctx);for(const name of ['autonomic-models.js','autonomic.js'])vm.runInContext(fs.readFileSync(path.join(root,'assets/js',name),'utf8'),ctx);
 assert.equal($('#receptors').children.length,8);assert.equal($('#dot').attrs.visibility,'hidden');assert.equal($('#resp').textContent,'0%');$('#move').onclick();assert.equal($('#dot').attrs.visibility,'visible');const effect=parseInt($('#resp').textContent);assert(effect>0);assert.equal($('#curve').attrs.points,$('#baseCurve').attrs.points);
 if(kind==='16'){assert(parseFloat($('#rateValue').textContent)>1);assert(parseFloat($('#forceValue').textContent)>1);assert(parseFloat($('#heart').style['--beat-duration'])<1.2);}if(kind==='17')assert(+( $('#airway').attrs.r)>58);if(kind==='18'){assert(parseFloat($('#rateValue').textContent)<1);assert(+$('#airway').attrs.r<58);assert(parseFloat($('#secretionValue').textContent)>1);}
 if($('#motionToggle')){$('#motionToggle').onclick();assert.equal($('#heart').style.animationPlayState,'paused');assert.equal($('#motionToggle').attrs['aria-pressed'],'true');}
 $('#antag').value='100';$('#antag').oninput();assert(parseInt($('#resp').textContent)<effect);assert(parseInt($('#blocked').textContent)>0);assert.notEqual($('#curve').attrs.points,$('#baseCurve').attrs.points);$('#agonist').value='0';$('#agonist').oninput();assert.equal($('#resp').textContent,'0%');assert.equal($('#on').textContent,'0 / 8');for(const key of ['rate','force','diameter','secretion'])if($('#'+key+'Value'))assert.equal($('#'+key+'Value').textContent,'1.00');
 $('#reset').onclick();assert.equal($('#agonist').value,'55');assert.equal($('#antag').value,'0');assert.equal($('#dot').attrs.visibility,'hidden');assert.equal($('#status').textContent,'結合前');assert.equal($('#curve').attrs.points.split(' ').length,101);console.log('PASS autonomic',kind,'binding / organ direction / competition / zero agonist / reset / graph');
}
