const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const root=path.resolve(__dirname,'..');
function run(sim,reduced=false){
 const registry=new Map(),inputs=[],targets=[];const media={matches:reduced,addEventListener(k,fn){this.changed=fn}};
 function element(){let html='';const el={value:'',textContent:'',attrs:{},dataset:{},style:{},animations:[],setAttribute(k,v){this.attrs[k]=String(v)},addEventListener(k,fn){this['on'+k]=fn},querySelector(selector){return selector==='svg'?this.svg:null},querySelectorAll(selector){return selector==='animate,animateTransform'?this.animations:[]},click(){this.onclick?.()}};Object.defineProperty(el,'innerHTML',{get(){return html},set(value){html=value;if(value.includes('<svg')){this.svg={paused:false,pauseAnimations(){this.paused=true},unpauseAnimations(){this.paused=false}};this.animations=Array.from(value.matchAll(/<animate(?:Transform)?\b/g),()=>({begins:0,beginElement(){this.begins++}}))}for(const match of value.matchAll(/<(input|button|output|p)[^>]*\bid="([^"]+)"[^>]*>/g)){const child=element(),tag=match[1],source=match[0];child.value=(source.match(/value="([^"]+)"/)||[])[1]||'';registry.set(match[2],child);if(tag==='input')inputs.push(child)}for(const match of value.matchAll(/<button[^>]*data-target="([^"]+)"[^>]*>/g)){const child=element();child.dataset.target=match[1];targets.push(child)}}});return el}
 for(const id of ['dynamicControls','dynamicVisual','dynamicMetrics','dynamicEffect','reset'])registry.set(id,element());
 const context={window:null,document:{body:{dataset:{sim}},getElementById:id=>registry.get(id),querySelectorAll:selector=>selector==='input'?inputs:selector==='[data-target]'?targets:[],createElement:element},location:{reload(){this.reloaded=true}},matchMedia:()=>media,console};context.window=context;vm.createContext(context);for(const file of ['expansion-models.js','expansion-labs.js'])vm.runInContext(fs.readFileSync(path.join(root,'assets/js',file),'utf8'),context);return{registry,targets,media,visual:registry.get('dynamicVisual')}
}
for(const reduced of [false,true]){
 const membrane=run('membrane',reduced);assert.match(membrane.visual.innerHTML,/animateTransform/);assert.match(membrane.visual.innerHTML,/K<\/text>/);assert.equal(membrane.visual.svg.paused,reduced);const button=membrane.registry.get('motion');button.click();assert.equal(membrane.visual.svg.paused,!reduced);
 const targets=run('targets',reduced);assert.match(targets.visual.innerHTML,/細胞内シグナル/);assert.match(targets.visual.innerHTML,/begin="indefinite"/);assert(targets.visual.animations.every(a=>a.begins===0));targets.targets.find(x=>x.dataset.target==='channel').click();assert.match(targets.visual.innerHTML,/イオンが通る/);assert.match(targets.visual.innerHTML,/repeatCount="1"/);assert(targets.visual.animations.every(a=>a.begins===1));targets.registry.get('replay').click();assert(targets.visual.animations.every(a=>a.begins===1));targets.targets.find(x=>x.dataset.target==='enzyme').click();assert.match(targets.visual.innerHTML,/生成物/);assert(targets.visual.animations.every(a=>a.begins===1));targets.targets.find(x=>x.dataset.target==='transporter').click();assert.match(targets.visual.innerHTML,/膜の反対側へ運ぶ/);assert(targets.visual.animations.every(a=>a.begins===1));
}
console.log('PASS: LAB 13 moving K ions with motion controls; LAB 20 starts one animation per target click or replay click and does not loop.');
