const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const root=path.resolve(__dirname,'..');const url='file://'+path.join(root,'pharmacology_lab_33_ischemic_heart_disease.html');
const imbalance=()=>p.locator('[data-balance]').evaluate(e=>e.classList.contains('is-ischemia'));const points=()=>p.locator('#demandLine').getAttribute('points');
for(const width of [1440,1280,390,320]){await p.setViewportSize({width,height:900});await p.goto(url);assert(!await imbalance());assert.equal(await points(),'');await p.locator('#exercise').click();assert(!await imbalance());await p.locator('#limited').click();assert(!await imbalance());await p.locator('#exercise').click();assert(await imbalance());await p.locator('#rest').click();assert(!await imbalance());
 await p.locator('#acute').click();assert(await imbalance());assert(await p.locator('[data-clot]').first().isVisible());await p.locator('#step').click();const old=await points();await p.locator('#exercise').click();assert.equal(await points(),old);await p.locator('#step').click();assert((await points()).startsWith(old+' '));
 await p.locator('#drugDetails summary').click();const lumen=await p.locator('[data-lumen]').getAttribute('d'),supply=await p.locator('[data-supply]').getAttribute('style');await p.locator('[data-drug=antiplatelet]').click();assert(await p.locator('[data-block]').isVisible());assert.equal(await p.locator('[data-supply]').getAttribute('style'),supply);assert(await p.locator('[data-clot]').first().isVisible());
 for(const drug of ['beta','nitrate','dhp','nondhp','none']){await p.locator(`[data-drug=${drug}]`).click();assert.equal(await p.locator(`[data-drug=${drug}]`).getAttribute('aria-pressed'),'true');assert.equal(await p.locator('[data-lumen]').getAttribute('d'),lumen);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} ${drug}`);}
 await p.locator('#motion').click();assert.equal(await p.locator('#coronaryMap').getAttribute('data-motion'),'paused');assert.equal(await p.locator('.heart-beat').evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await p.locator('#reset').click();assert(!await imbalance());assert.equal(await points(),'');assert(!await p.locator('[data-clot]').first().isVisible());
 await p.locator('#drugDetails summary').click();await p.locator('#limited').click();await p.locator('#exercise').click();if(width===1440||width===390)await p.screenshot({path:path.join(__dirname,`ischemia-${width}.png`),fullPage:true});console.log('PASS LAB 33 viewport',width,'main bottom',await p.locator('#experiment').evaluate(e=>e.getBoundingClientRect().bottom+scrollY));
 assert.equal(await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.length===new Set(ids).size}),true);
}
await p.locator('#record').click();await p.waitForTimeout(1100);await p.locator('#record').click();const frozen=await points();await p.waitForTimeout(600);assert.equal(await points(),frozen);assert(frozen.split(' ').length>=3);await p.locator('#clearHistory').click();assert.equal(await points(),'');await p.locator('#acute').click();for(let i=0;i<35;i++)await p.locator('#step').click();assert.match(await p.locator('#injury').textContent(),/不可逆的/);for(let i=35;i<120;i++)await p.locator('#step').click();assert(await p.locator('#step').isDisabled());assert(await p.locator('#record').isDisabled());
await p.goto(url);
const change=async(id,value)=>p.locator('#'+id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},value);
await change('oxygen',10);assert(await imbalance());await change('oxygen',100);assert(!await imbalance());await change('wall',100);assert.match(await p.locator('[data-wall]').textContent(),/増加/);await change('hr',100);assert.match(await p.locator('[data-perfusion]').textContent(),/短縮/);
await p.locator('#reset').click();await p.locator('#limited').click();await p.locator('#exercise').click();await p.locator('#step').click();await p.locator('#rest').click();await p.locator('#step').click();assert.match(await p.locator('#injury').textContent(),/回復する方向/);
await p.evaluate(()=>{const div=document.createElement('div');div.id='secondMap';document.body.append(div);window.CORONARY_HEART.mount(div).render(window.ISCHEMIA_MODEL.state({thrombus:true}),{motion:false});});assert(await p.locator('#secondMap [data-clot]').first().isVisible());assert(!await p.locator('#coronaryMap [data-clot]').first().isVisible());
await p.emulateMedia({reducedMotion:'reduce'});await p.goto(url);assert.equal(await p.locator('#coronaryMap').getAttribute('data-motion'),'paused');assert.equal(await p.locator('.heart-beat').evaluate(e=>getComputedStyle(e).animationName),'none');
await p.goto('file://'+path.join(root,'pharmacology_lab_32_heart_failure_drugs.html'));assert.equal(await p.locator('.lab-navigation a[href="pharmacology_lab_33_ischemic_heart_disease.html"]').count(),1);await p.locator('.lab-navigation a[href="pharmacology_lab_33_ischemic_heart_disease.html"]').click();assert(await p.locator('h1').textContent()==='虚血性心疾患');assert.deepEqual(errors,[]);await b.close();console.log('PASS LAB 33 browser: presets, drug targets, history append/pause/end/reset, clot persistence, motion, responsive and navigation');})().catch(e=>{console.error(e);process.exit(1)});
