const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'assets/js/nephron-model.js'),'utf8'),ctx);const M=ctx.window.NEPHRON_MODEL;
assert.equal(M.SEGMENTS.length,7);assert.equal(M.SEGMENTS.find(x=>x.id==='proximal').na,67);assert.equal(M.SEGMENTS.find(x=>x.id==='thick-ascending').water,0);assert.equal(M.SEGMENTS.find(x=>x.id==='thick-ascending').transporter,'NKCC2');assert.equal(M.SEGMENTS.find(x=>x.id==='distal').transporter,'NCC');
const normal=M.simulate({adh:1,drugClass:'none'}),adhOff=M.simulate({adh:0,drugClass:'none'});assert(normal.urineNa<5);assert(adhOff.urineWater>normal.urineWater);assert.equal(normal.stages[3].remainingNa,8);assert.equal(normal.stages[3].remainingWater,19);
for(const id of ['loop','thiazide','mra','enac','ca','sglt2']){const s=M.simulate({adh:1,drugClass:id});assert(s.urineNa>normal.urineNa,`${id} should increase urinary sodium direction`);assert(s.urineWater>normal.urineWater,`${id} should increase water excretion direction without fixed 1:1 coupling`);assert(s.distalNaDelivery>0);assert(s.stages.some(x=>x.blocked))}
const loop=M.simulate({adh:1,drugClass:'loop'}),thiazide=M.simulate({adh:1,drugClass:'thiazide'}),osmotic=M.simulate({adh:1,drugClass:'osmotic'});assert(loop.urineNa>thiazide.urineNa);assert(osmotic.urineWater>normal.urineWater);assert.equal(M.DRUGS.mra.target,'MR');assert.equal(M.DRUGS.enac.target,'ENaC');assert.notEqual(M.DRUGS.mra.target,M.DRUGS.enac.target);
const catalog=JSON.parse(fs.readFileSync(path.join(root,'assets/js/catalog.js'),'utf8').split('=')[1].trim().replace(/;$/,''));for(const [id,label] of [['nephron','36'],['diuretic-sites','37']]){const lab=catalog.find(x=>x.id===id);assert(lab);assert.equal(lab.label,label);assert(fs.existsSync(path.join(root,lab.href)))}assert(catalog.findIndex(x=>x.id==='diuretic-sites')===catalog.findIndex(x=>x.id==='nephron')+1);
for(const file of ['pharmacology_lab_36_nephron.html','pharmacology_lab_37_diuretic_sites.html']){const html=fs.readFileSync(path.join(root,file),'utf8');for(const asset of ['assets/js/nephron-model.js','assets/js/nephron-view.js','assets/css/nephron.css'])assert(html.includes(asset));assert.match(html,/学習用モデル/)}
console.log('PASS: LAB 36/37 shared nephron model, ADH, segment handling, seven drug classes, downstream sodium, navigation and safety text.');
