const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const root=path.resolve(__dirname,'..'),url='file://'+path.join(root,'pharmacology_lab_34_arrhythmia.html');await p.clock.install();await p.clock.pauseAt(new Date());const run=ms=>p.clock.runFor(ms),points=()=>p.locator('[data-ecg]').getAttribute('points');
for(const width of [1440,1280,390,320]){await p.setViewportSize({width,height:900});await p.goto(url);assert.equal(await points(),'');assert(await p.locator('#pause').isDisabled());assert(await p.locator('#ectopic').isDisabled());assert.equal(await p.locator('#drugDetails').getAttribute('open'),null);await p.locator('#start').click();await run(900);assert.equal(await p.locator('#electricalHeart').getAttribute('data-stage'),'av');assert.match(await p.locator('.current-stage').textContent(),/少し待つ/);await run(600);assert.equal(await p.locator('#electricalHeart').getAttribute('data-ventricular-contraction'),'false');await run(220);assert.equal(await p.locator('#electricalHeart').getAttribute('data-ventricular-contraction'),'true');
 await p.locator('#pause').click();const old=await points();await run(900);assert.equal(await points(),old);await p.locator('#avSpeed').evaluate(e=>{e.value=0;e.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await points(),old);await p.locator('#step').click();assert((await points()).startsWith(old+' '));
 await p.locator('#zoom').click();assert(await p.locator('#cellDetails').evaluate(e=>e.open));assert.match(await p.locator('[data-ap-caption]').textContent(),/心室筋/);await p.locator('#nodeCell').click();assert.match(await p.locator('[data-ap-caption]').textContent(),/洞結節/);
 await p.locator('#drugDetails summary').click();for(const id of ['na','beta','k','ca','none']){await p.locator(`[data-drug=${id}]`).click();assert.equal(await p.locator(`[data-drug=${id}]`).getAttribute('aria-pressed'),'true');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} ${id}`);if(['beta','ca'].includes(id))assert.match(await p.locator('[data-ap-caption]').textContent(),/洞結節/);}
 await p.locator('#reset').click();await p.locator('#drugDetails summary').click();await p.locator('#cellDetails summary').click();await p.locator('#start').click();await run(900);await p.locator('#pause').click();
 console.log('PASS LAB 34 viewport',width,'main bottom',await p.locator('#experiment').evaluate(e=>e.getBoundingClientRect().bottom+scrollY));if(width===1440||width===390){await p.locator('#experiment').screenshot({path:path.join(__dirname,`rhythm-${width}.png`)});await p.locator('.rhythm-observe').screenshot({path:path.join(__dirname,`rhythm-observe-${width}.png`)});}assert.equal(await p.evaluate(()=>{const x=[...document.querySelectorAll('[id]')].map(e=>e.id);return x.length===new Set(x).size}),true);
}
await p.locator('#reset').click();await p.locator('#weaken').click();await p.locator('#weaken').click();await p.locator('#start').click();await run(5800);assert.match(await p.locator('#weakState').textContent(),/一部が途絶/);assert.equal(await p.locator('.ecg-wave-label').filter({hasText:/^P$/}).count(),2);assert.equal(await p.locator('.ecg-wave-label').filter({hasText:/^QRS$/}).count(),1);
await p.locator('#reset').click();await p.locator('#start').click();await run(2000);await p.locator('#ectopic').click();assert(await p.locator('#ectopic').isDisabled());await run(600);assert(await p.locator('[data-ectopic]').evaluate(e=>e.getAttribute('visibility')==='visible'));await run(500);assert(!(await p.locator('#ectopic').isDisabled()));
await p.locator('#advanced summary').click();for(const mode of ['af','reentry','vt','vf','normal']){await p.locator(`[data-mode=${mode}]`).click();assert.equal(await points(),'');assert.equal(await p.locator('#runState').textContent(),'待機中');await p.locator('#start').click();await run(6500);await p.locator('#pause').click();assert.equal(await p.locator(`[data-mode=${mode}]`).getAttribute('aria-pressed'),'true');if(mode==='af'){assert.equal(await p.locator('.ecg-wave-label').filter({hasText:/^P$/}).count(),0);assert.match(await p.locator('#hrMetric').textContent(),/不規則/);assert(await p.locator('[data-atrial-chaos]').isVisible());assert(!(await p.locator('[data-vent-chaos]').isVisible()));assert(await p.locator('[data-af-filter]').isVisible());}if(mode==='reentry')assert(await p.locator('[data-circuit]').isVisible());if(mode==='vf'){assert.equal(await p.locator('.ecg-wave-label').count(),0);assert.match(await p.locator('#coMetric').textContent(),/著しく低下/);}assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,mode);}
await p.locator('#reset').click();await p.locator('#start').click();await run(52000);assert.equal(await p.locator('#runState').textContent(),'記録終了');assert(await p.locator('#step').isDisabled());assert(await p.locator('#pause').isDisabled());assert.equal((await points()).trim().split(' ').at(-1).split(',')[0],'780');await p.locator('#reset').click();assert.equal(await points(),'');
await p.emulateMedia({reducedMotion:'reduce'});await p.goto(url);assert.equal(await p.locator('#runState').textContent(),'待機中');const transform=await p.locator('[data-chamber=atria]').getAttribute('style');await run(3000);assert.equal(await p.locator('[data-chamber=atria]').getAttribute('style'),transform);await p.locator('#step').click();assert((await points()).length>0);
await p.goto('file://'+path.join(root,'pharmacology_lab_33_ischemic_heart_disease.html'));assert.equal(await p.locator('.coronary-heart').count(),1);assert((await p.locator('.heart-beat>path').first().getAttribute('d')).startsWith('M170'));await p.locator('.lab-navigation a[href="pharmacology_lab_34_arrhythmia.html"]').click();assert.equal(await p.locator('h1').textContent(),'不整脈');assert.deepEqual(errors,[]);await b.close();console.log('PASS LAB 34 browser: synchronization, pause/history, cells/drugs, partial block, ectopy, independent modes, endpoint/reset, reduced motion and navigation');})().catch(e=>{console.error(e);process.exit(1)});
