const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../assets/js/rhythm-model.js','utf8'),c);const M=c.window.RHYTHM_MODEL;
function run(input={},end=18){const e=M.create();e.reset(input);let s=e.snapshot();const snapshots=[];while(s.t<end-.001){s=e.step(.025,input);snapshots.push(s);}return {e,s,snapshots};}
let a=run();const b=a.s.beats[0];assert(b.origin<b.a&&b.a<b.av&&b.av<b.v);assert(a.snapshots.some(s=>s.stage==='av'));const avStates=a.snapshots.filter(s=>s.stage==='av');assert(avStates.length>=10);assert(!a.snapshots.find(s=>s.t>=b.a&&s.t<b.a+.1).atrialContract);assert(a.snapshots.some(s=>s.t>b.a+.16&&s.atrialContract));assert(!a.snapshots.find(s=>s.t>=b.v&&s.t<b.v+.1).ventricularContract);assert(a.snapshots.some(s=>s.t>b.v+.15&&s.ventricularContract));
assert(run({speed:100}).s.beats.length>a.s.beats.length);assert(run({speed:0}).s.beats.length<a.s.beats.length);assert(run({av:0}).s.beats[0].v-b.a>b.v-b.a);
const partial=run({weak:2});assert(partial.s.beats.some(b=>b.blocked&&b.v===null));assert(partial.snapshots.some(s=>s.stage==='blocked'));const blocked=partial.s.beats.find(b=>b.blocked);assert.equal(M.ecg(blocked.av+blocked.p.delay+.3,[blocked],'normal'),0);
const beta=run({drug:'beta'});assert(beta.s.beats.length<a.s.beats.length);assert(beta.s.beats[0].v-beta.s.beats[0].a>b.v-b.a);assert(M.parameters({drug:'ca'}).delay>M.parameters().delay);assert(M.parameters({drug:'na'}).qrs>M.parameters().qrs);assert(M.ventricularAP(.04,'na').value<M.ventricularAP(.04).value);assert.equal(M.ventricularAP(1.2).phase,4);assert(M.ventricularAP(1.2,'k').phase!==4);assert.match(M.nodalAP(.06,M.parameters()).ion,/Ca/);assert.match(M.ventricularAP(.02).ion,/Na/);assert.equal(M.ventricularAP(.4).phase,2);
const af=run({mode:'af'});assert(af.s.beats.every(b=>b.a===null));const vv=af.s.beats.filter(b=>b.v!==null).map(b=>b.v);assert(new Set(vv.slice(1).map((x,i)=>(x-vv[i]).toFixed(2))).size>3);assert(!af.snapshots.some(s=>s.atrialContract));assert(af.snapshots.some(s=>s.ventricularContract));assert.equal(af.s.circulation.hr,'不規則');const afBeta=run({mode:'af',drug:'beta'});assert(afBeta.s.beats.length<af.s.beats.length);
for(const mode of ['reentry','vt','vf']){const x=run({mode});assert.equal(x.s.p.mode,mode);if(mode==='vf'){assert.equal(x.s.beats.length,0);assert(!x.snapshots.some(s=>s.ventricularContract));assert.equal(x.s.circulation.rate,0);}else assert(x.s.beats.length>0);}
const ect=run({},2);assert(ect.e.ectopic());assert(!ect.e.ectopic());let s=ect.s;while(s.t<5)s=ect.e.step(.025,{});const extra=s.beats.find(b=>b.kind==='ectopic');assert(extra&&extra.v!==null);assert(extra.v<s.beats.find(x=>x.kind==='sinus'&&x.origin>b.origin).v);assert(s.beats.some(b=>b.kind==='sinus'));assert.equal(ect.e.reset().beats.length,0);
assert(run({speed:100}).s.circulation.sv==='低下し得る');for(const speed of [0,100])for(const av of [0,100])for(const drug of Object.keys(M.drugs)){const s=run({speed,av,drug},5).s;assert(Number.isFinite(s.ecg));assert(Number.isFinite(s.ventAP.value));assert(Number.isFinite(s.nodeAP.value));}
console.log('PASS LAB 34: conduction order, AV dwell/PR, electrical-before-mechanical, sinus rate, partial block, ectopy, AF irregularity, separate VT/VF/reentry, distinct APs/drugs, filling and bounds');
